spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres 
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    config:
      enabled: false
